tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/server.crt
        keyFile: /certs/server.key

  certificates:
    - certFile: /certs/n8n.crt
      keyFile: /certs/n8n.key
